# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME', 'fish') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'fish-psql') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

development:
  <<: *default
  database: rails_auth_db_development

test:
  <<: *default
  database: rails_auth_db_test

production:
  <<: *default
  database: rails_auth_db_production
  username: <%= ENV['RAILS_AUTH_DB_USERNAME'] %>
  password: <%= ENV['RAILS_AUTH_DB_PASSWORD'] %>
